### ISSUE TITLE
Showing blank page.

### ISSUE THREAD

**Issue by ephraimlambarte** [yassine-khachlek/laravel-ocr#1]
I am using laravel 5.6 and i followed all your instructions but i get a blank page when i try to render the text.

**Comment by DalbirKaur** [comment]
same issue. Any lead?

**Comment by ephraimlambarte** [comment]
@DalbirKaur  no leads for this. i used azure ocr services instead. they will give you free 200$ credits for testing it.

**Comment by DalbirKaur** [comment]
Ok, Thanks.
